[project]
name = "pyloid-app"
version = "0.1.0"
description = "pyloid project!"
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
    "pyloid>=0.23.19",
    "pyloid-builder>=0.1.0",
    "plotly>=6.0.1",
    "numpy>=2.0.2",
]
